name: Build Executables with PyInstaller

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  pyinstaller-build-win:
    runs-on: windows-latest
    steps:
      - name: PyInstaller Action
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13'
          spec: 'src/wav2polaris/wav2polaris.py'
          requirements: 'build-requirements.txt'
          options: --onefile, --name "wav2polaris", --icon wav2polaris.png
          upload_exe_with_name: 'wav2polaris-win'
  pyinstaller-build-mac:
    runs-on: macos-latest
    steps:
      - name: PyInstaller Action
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13'
          spec: 'src/wav2polaris/wav2polaris.py'
          requirements: 'build-requirements.txt'
          python_arch: 'universal2'
          options: --onefile, --name "wav2polaris", --icon wav2polaris.png
          upload_exe_with_name: 'wav2polaris-mac'
