name: Build Executables with PyInstaller

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  pyinstaller-build-win:
    runs-on: windows-latest
    steps:
      - name: PyInstaller Action
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13.2'
          spec: 'wav2polaris-win.spec'
          requirements: 'build-requirements.txt'
          #options: --onefile, --name "wav2polaris", --icon wav2polaris.png, --collect-submodules wav2polaris
          upload_exe_with_name: 'wav2polaris-win'
  pyinstaller-build-mac-arm64:
    runs-on: macos-latest
    steps:
      - name: PyInstaller Action
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13.2'
          spec: 'wav2polaris-arm64.spec'
          requirements: 'build-requirements.txt'
          python_arch: 'arm64'
          #options: --onefile, --name "wav2polaris", --icon wav2polaris.png
          upload_exe_with_name: 'wav2polaris-mac-arm64'
  pyinstaller-build-mac-x86_64:
    runs-on: macos-13
    steps:
      - name: PyInstaller Action
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.13.2'
          spec: 'wav2polaris-x86_64.spec'
          requirements: 'build-requirements.txt'
          python_arch: 'x64'
          #options: --onefile, --name "wav2polaris", --icon wav2polaris.png
          upload_exe_with_name: 'wav2polaris-mac-x86_64'

  generate-universal-mac-binary:
    runs-on: macos-latest
    needs: [pyinstaller-build-mac-arm64, pyinstaller-build-mac-x86_64]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        id: download-artifacts
        with:
          path: ./working-dir
          pattern: wav2polaris-mac-*
          merge-multiple: true
      - name: Unzip Artifacts
        working-directory: ./working-dir
        run: |
          unzip wav2polaris-mac-arm64.zip
          unzip wav2polaris-mac-x86_64.zip
      - name: Combine into Universal Binary
        working-directory: ./working-dir
        run: lipo -create wav2polaris-x86_64 wav2polaris-arm64 -output wav2polaris
      - name: Upload Universal Binary
        uses: actions/upload-artifact@v4
        with:
          path: ./working-dir/wav2polaris
          name: wav2polaris-mac-universal2